apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
stringData:
  # Refer to  https://www.mongodb.com/docs/cluster-to-cluster-sync/current/reference/configuration/#configuration
  # for more options.
  mongosync.yml: |
    cluster0: "mongodb://mongosync-user:<strong-password>@mongos.mongodb.svc.cluster.local:27017"
    cluster1: "mongodb://mongosync-user:<strong-password>@127.0.0.1:27017"
    logPath: "/var/log/mongosync"
    verbosity: "WARN"
